### ISSUE TITLE
b站推送排除关键词功能没用

### ISSUE THREAD

**Issue by skelfu** [xianxincoder/xianxin-plugin#10]
rt，包含关键词任然推送，
![WI)PC5BL0V3CR@_044B}P)K](https://user-images.githubusercontent.com/34668097/192098782-b4e967b5-c2d2-4c71-8cca-3996a2e0d60c.png)
![157ZZNKD6~WPR`1YXB3J6T0](https://user-images.githubusercontent.com/34668097/192098785-8201eaec-0ff5-4e7a-b825-cfa946655369.png)

**Comment by skelfu** [comment]
试了试，应该是`data.data.title`和`data.data.content`

**Comment by xianxincoder** [comment]
感谢反馈，确实是这样，已修复 更新一下插件即可
