### ISSUE TITLE
发表情包就被禁言是怎么回事

### ISSUE THREAD

**Issue by jiexi22** [xianxincoder/xianxin-plugin#12]
看日志也没显示 
禁言时间是随机的 什么都没说 只发了个表情包就被禁了

**Comment by xianxincoder** [comment]
新更新的功能，回复一个消息 戳|撤|禁|踢 就会记录下来下次还是会执行这个操作
更新一下插件 发送 #快管列表看看
如果有内容的话 可以#快管删除+内容删除掉 就不会禁用了
