### ISSUE TITLE
建议b站推送加上屏蔽词

### ISSUE THREAD

**Issue by lin-junliang** [xianxincoder/xianxin-plugin#13]
如果检测到文章中有“互动抽奖”字样则不推送。
原神官方帐号的抽奖频率非常高，容易导致相同的内容发3次（原文一次，抽奖一次，中奖一次）造成信息骚扰。
如果能添加自定义屏蔽词就更好了，以免后续出现更多广告性质的推送

**Comment by xianxincoder** [comment]
可以设置的 Yunzai-Bot/plugins/xianxin-plugin/config/bilibili.set.yaml
![image](https://user-images.githubusercontent.com/109654219/195476540-7a8e3232-3dbe-4d70-85ee-3eb839d292f5.png)
