### ISSUE TITLE
关于直播推送的延迟

### ISSUE THREAD

**Issue by weilai5201314** [xianxincoder/xianxin-plugin#15]
在b站推送这一块，动态推送和直播推送的延迟不太一样。

我设置了3分钟推送一次。

- 动态推送，推送很及时，基本上发了几分钟就会推送。
- 直播推送，基本上每次都是开播了十几分钟才会显示（测试了三四个人）。

想问问需要修改其他设置吗？

<img width="688" alt="image" src="https://user-images.githubusercontent.com/99032101/202896407-3016b968-6c25-4423-8a89-4cdbf6e7c974.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/99032101/202896253-18c46b32-912a-460a-8162-30fbc067fd31.png">

**Comment by xianxincoder** [comment]
确实是这样的，直播接口变动数据会有延迟，之前用的接口可以解决不过后来被b站给限制了。目前这个接口是这样的
