### ISSUE TITLE
关于B站的推送功能

### ISSUE THREAD

**Issue by shushuaaa125** [xianxincoder/xianxin-plugin#3]
请问 推送动态、图文、视频、直播、转发有独立出来的开关可以使用吗。比如说只需要某个UP推送直播动态，不需要看其他的图文、视频推送这样的。

**Comment by xianxincoder** [comment]
确实有这种需求，我来想想办法

**Comment by xianxincoder** [comment]
Yunzai-Bot/plugins/xianxin-plugin/config/bilibili.push.yaml
上面路径的配置文件下，配置字段type数组，可以限制只推送某几个动态模块哈，删除type则全部推送

动态模块枚举如下
直播动态为 DYNAMIC_TYPE_LIVE_RCMD
转发动态为 DYNAMIC_TYPE_FORWARD
文章动态为 DYNAMIC_TYPE_ARTICLE
文字动态为 DYNAMIC_TYPE_WORD
视频动态为 DYNAMIC_TYPE_AV

比如下图，就只推送直播信息
![image](https://user-images.githubusercontent.com/109654219/185333628-2523df6d-a205-46cf-b97d-0f6392ce11ff.png)

**Comment by shushuaaa125** [comment]
type可以同时 DYNAMIC_TYPE_LIVE_RCMD
转发动态为 DYNAMIC_TYPE_FORWARD

**Comment by xianxincoder** [comment]
可以的 是数组，这样的话，就是推送这两个模块

**Comment by xianxincoder** [comment]
注意 - 后面有个空格哈，这是yaml的格式

**Comment by shushuaaa125** [comment]
emmmm 不知道为什么，按上面设置好之后一直没推送。我添加的环球网来测视频动态

**Comment by xianxincoder** [comment]
你放一个你配置文件的内容图片 我看一下

**Comment by shushuaaa125** [comment]
![QQ图片20220819215934](https://user-images.githubusercontent.com/111445252/185635541-82b59475-784a-45de-9a03-b79df6da1938.png)

**Comment by shushuaaa125** [comment]
![image](https://user-images.githubusercontent.com/111445252/185636424-07e6676d-abaa-4117-a71a-05a837162a29.png)

**Comment by xianxincoder** [comment]
看着没问题，是现在设置之后全部不推送了嘛

**Comment by shushuaaa125** [comment]
目前是几乎没推送的状态，昨晚机器人就在一个群里发了一条环球网的，其他群的几乎都不推了。前天则是在另一个群只发了一条。其他群的推送的B站对象有动态但机器人没推送反应。

**Comment by xianxincoder** [comment]
我测试了一下，应该没什么问题，估计你是不是报错了，type下面的值很容易格式报错，你可以node app 启动下云崽看看，插件是否正常加载了，比如下图这样。或者看一下错误日志有没有错误 
![image](https://user-images.githubusercontent.com/109654219/185736134-f8039d6d-12bc-460e-bdb5-113944109cfd.png)

**Comment by shushuaaa125** [comment]
我大概知道是为什么了，我的新号机器人被风控发不出消息
