### ISSUE TITLE
神秘代码的图源可以自行增添吗

### ISSUE THREAD

**Issue by SkinnyLi** [xianxincoder/xianxin-plugin#7]
找了一下没找到在哪个配置文件里，还想丰富一下网址来着（不是）

**Comment by xianxincoder** [comment]
要接口返回数据结构一样才能用，是word press的网站 应该问题不大，不过不想开放在配置文件里，怕乱改地址，也不知道支不支持，就改坏了。如果有合适的 可以提供出来看看

**Comment by xianxincoder** [comment]
要接口返回数据结构一样才能用，是word press的网站 应该问题不大，不过不想开放在配置文件里，怕乱改地址，也不知道支不支持，就改坏了。如果有合适的 可以提供出来看看
