### ISSUE TITLE
修改defSet/tools/set.yaml中的字段没有用

### ISSUE THREAD

**Issue by TaisZ** [xianxincoder/xianxin-plugin#9]
我尝试开启私聊神秘空间的设置,并且开发权限给所有人, 但是我更改set.yaml之后并没有应用. 还是只能主人触发神秘空间

**Comment by TaisZ** [comment]
应该是是apps/tools.js中第11行代码 :
`let toolsSetFile = "./plugins/xianxin-plugin/config/tools.set.yaml"`
路径写错了,"/"写成了"."

**Comment by xianxincoder** [comment]
Yunzai-Bot/plugins/xianxin-plugin/config/tools.set.yaml
修改这个文件哈，你改错文件了。defset时默认设置文件，会被config里的文件覆盖掉

**Comment by xianxincoder** [comment]
代码也没有错，就是这么写的
